version: '3.6'
services: 
    web:
        build: .
        container_name: User_Identity
        #  mount this image as volume to don't rebuild the image all the time.
        volumes: 
            - .:/code
        environment: 
            FLASK_DEBUG: 1
            FLASK_ENV: devalopment
        entrypoint: 
            - python
            - app.py
        ports: 
            - "5000:5000"
        networks: 
            net_:



networks: 
    # create Network By Default with directory name
    net_: